{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.destinationRule.name }}
  namespace: {{.Values.namespace}}
spec:
  host: {{ .Values.destinationRule.host }}
  trafficPolicy:
    tls:
      mode: {{ .Values.destinationRule.tls.mode }}
{{- end }}