{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{.Values.namespace}}
spec:
  selector:
    istio: ingressgateway # Use Istio's default ingress gateway
  servers:
    - port:
        number: {{ .Values.gateway.port }}
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.gateway.hosts | join ", " }}

  {{- end }}
