apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  ports:
    - port: 5432
  selector:
    app: {{ .Values.postgres.name }}
