apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.productService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.productService.name }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Values.productService.name }}
